### ISSUE TITLE
抓取报错：序列越界

### ISSUE THREAD

**Issue by leonxcom** [CuiBinghua/douban_list_spider#1]
测试爬虫脚本时，以`日本动画`作为标签进行抓取，会报如下错误：

```
准备开始抓取...
正在抓取日本动画的第1页信息...
正在抓取日本动画的第2页信息...
正在抓取日本动画的第3页信息...
正在抓取日本动画的第4页信息...
正在抓取日本动画的第5页信息...
正在抓取日本动画的第6页信息...
正在抓取日本动画的第7页信息...
Traceback (most recent call last):
  File "douban_list_spider.py", line 190, in <module>
    main()
  File "douban_list_spider.py", line 186, in main
    do_spider()
  File "douban_list_spider.py", line 164, in do_spider
    douban_spider(douban_tag)
  File "douban_list_spider.py", line 158, in douban_spider
    each_page_spider(douban_tag, page)
  File "douban_list_spider.py", line 143, in each_page_spider
    movie_spider(soup, item_num)
  File "douban_list_spider.py", line 76, in movie_spider
    time_info =     '上映时间：    ' + desc_list[-5]
IndexError: list index out of range
```

**Comment by CuiBinghua** [comment]
嗯，谢谢亲的测试。
主要是豆瓣某些条目提供的信息不全，没法进行正确分解。
我已修改代码，信息太少的条目，直接就不分解了。
谢谢！

**Comment by ArtinHuang** [comment]
@CuiBinghua  修改之后，感觉抓取速度比之前慢上了许多，这是为何？
